console.log('Supercalifragilisticexpialidocious'.length);
console.log(5);
console.log(typeof(5));
console.log(23n);
console.log(typeof(23n));
var nfl = 'dallas cowboys';
var nba = 'los angelos lakers';
console.log(`I like the ${nfl} and ${nba}`);
let children = 1;
let partnerName = "Vanessa";
let location = 'Alexandria, VA';
let job = "Software Engineer Student";
console.log(`You will be a ${job} in ${location}, and married to ${partnerName} with ${children} kid.`);
let birthYear = 1990;
let futureYear = 2035;
console.log(`I will be either ${futureYear - birthYear - 1} or ${futureYear - birthYear} in ${birthYear}.`);
